name: "Publish AUR Package (stabldev)"
description: "Generate and publish PKGBUILD to AUR"
author: "stabldev"
inputs:
  pkgname:
    description: "AUR package name"
    required: true
  pkgver:
    description: "AUR package version"
    required: true
  pkgbuild_template:
    description: "Path to PKGBUILD template"
    required: false
    default: "./pkgbuild-template/PKGBUILD"
  commit_username:
    description: "The username to use when creating new commit"
    required: false
    default: "github-actions[bot]"
  commit_email:
    description: "The email to use when creating new commit"
    required: false
    default: "41898282+github-actions[bot]@users.noreply.github.com"
  aur_ssh_private_key:
    description: "Your private key with access to AUR package."
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
